import ast
from dataclasses import MISSING, dataclass, field, fields, is_dataclass
from pathlib import Path
from typing import Any
from omegaconf import OmegaConf


@dataclass(slots=True)
class ArchiveConfig:
    n_h_bins: int = 6
    n_div_bins: int = 6
    h_range: tuple[float, float] = (0.0, 6.0)
    diversity_axis: str = "concept_group"
    epsilon: float = 0.3
    ucb_c: float = 1.0
    selection_strategy: str = "ucb"


@dataclass(slots=True)
class EvolutionConfig:
    seed_programs_dir: str = "seed_programs"
    inner_iterations: int = 8
    inner_iteration_batch_size: int = 4
    num_rollouts: int = 4
    in_depth_ratio: float = 0.5
    verify_seeds: int = 5
    frontier_p_hat_range: tuple[float, float] = (0.1, 0.9)
    # When True, a child that parses but fails verification gets ONE multi-turn
    # self-fix attempt: the model is shown its own program + the rejection reason
    # and asked to fix only that issue.
    fix_retry: bool = True
    # When True, every lint-verified child (including fix-retry survivors) passes
    # an LLM coherence gate on its seed-0 problem before solver rollout / archive
    # insertion. A problem the evaluator marks INVALID is discarded -- a final
    # noise filter against incoherent statements that pass the cheap lint checks.
    use_evaluator: bool = True
    # "policy" keeps the legacy behavior: evaluator prompts are generated by the
    # current rollout policy. "openai" sends the same evaluator prompt to the
    # OpenAI Responses API instead, so the gate is independent of the trained
    # policy being evaluated.
    evaluator_provider: str = "policy"
    evaluator_model: str = "gpt-5.4-mini"
    evaluator_reasoning_effort: str = "low"
    evaluator_timeout_s: float = 60.0
    evaluator_max_output_tokens: int = 512
    # Ablation: drop the H/uncertainty term ONLY from the priority that drives
    # evolution -- which champions are picked as mutation parents and which are
    # drained into the training batch -- so those decisions rank by s(1-s)
    # (pass-rate variance) instead of s(1-s)*H. The MAP still bins on real H and
    # stores/logs each champion's real R_Q, so the archive snapshots show the
    # true scores; only the selection ranking ignores H. This isolates whether
    # H is actually needed to drive the curriculum. Production keeps this False.
    select_ignores_uncertainty: bool = False

    # Ablation (the mirror of select_ignores_uncertainty): drop the s(1-s)
    # pass-rate-variance term ONLY from the selection/mutation priority, so those
    # decisions rank by H (uncertainty) alone instead of s(1-s)*H. The MAP still
    # bins on real H and stores/logs each champion's real R_Q. Isolates whether
    # the pass-rate-variance term is needed to drive the curriculum. Do NOT set
    # this together with select_ignores_uncertainty (that leaves no signal).
    select_ignores_variance: bool = False

    def __post_init__(self) -> None:
        if self.evaluator_provider not in ("policy", "openai"):
            raise ValueError(
                "evolution.evaluator_provider must be 'policy' or 'openai', "
                f"got {self.evaluator_provider!r}"
            )
        if self.evaluator_reasoning_effort not in ("minimal", "low", "medium", "high"):
            raise ValueError(
                "evolution.evaluator_reasoning_effort must be one of "
                "minimal|low|medium|high"
            )
        if self.evaluator_timeout_s <= 0:
            raise ValueError("evolution.evaluator_timeout_s must be > 0")
        if self.evaluator_max_output_tokens < 1:
            raise ValueError("evolution.evaluator_max_output_tokens must be >= 1")


@dataclass(slots=True)
class TrainingDataConfig:
    instances_per_program: int = 8
    training_budget: int | None = None
    strict_anti_reuse: bool = True
    # Order in which frontier champions are drained into the training batch.
    #   False (default) -> highest R_Q first (production behavior).
    #   True            -> lowest R_Q first (ablation: invert the priority so the
    #                      budget binds on the LEAST uncertain/valuable champions).
    select_lowest_rq_first: bool = False
    # ABLATION: ignore R_Q ordering entirely and drain frontier champions in a
    # RANDOM order (no sort). Takes precedence over select_lowest_rq_first when
    # both are set. The shuffle is seeded (select_random_seed + refresh count) so
    # runs are reproducible while still varying across outer iterations.
    select_random_order: bool = False
    select_random_seed: int = 0


@dataclass(slots=True)
class VerlConfig:
    enabled: bool = False
    config_path: str | None = None
    reward_function: str = "./src/rq_evolve/reward.py:compute_score"
    evolve_on_first_epoch: bool = True


@dataclass(slots=True)
class AsyncRolloutConfig:
    """Streaming (producer-consumer) evolve-phase rollout settings.

    ``streaming_enabled: false`` restores the legacy whole-batch path exactly
    (one blocking ``generate_sequences`` for the full inner batch). When true,
    solver rollouts are split into chunks of ``chunk_size`` instances (each
    chunk carries ``chunk_size * num_rollouts`` requests), submitted round-robin
    to verl's agent-loop workers with at most ``max_in_flight_chunks`` chunks
    outstanding, and verification/filtering/logging consume each chunk as soon
    as IT finishes -- a short problem's chunk is never blocked behind another
    chunk's long generations.
    """

    streaming_enabled: bool = True
    # Instances per chunk. 1 = finest granularity: one problem's G rollouts per
    # chunk, so its verification starts the moment its own rollouts finish.
    chunk_size: int = 1
    # Backpressure: max chunks outstanding in the rollout engine at once.
    max_in_flight_chunks: int = 8
    # Per-chunk wall-clock budget (covers queueing + generation of the chunk's
    # slowest sample). On expiry the chunk is retried up to max_retries times,
    # then recorded as a failure with reason "timeout" -- never silently dropped.
    request_timeout_s: float = 900.0
    max_retries: int = 1
    # CPU threads consuming completed chunks (math_verify + filtering + JSONL).
    verify_workers: int = 4
    # Bound on the completed-chunk queue between scheduler and verifiers; when
    # full, submission pauses (backpressure) instead of buffering unboundedly.
    queue_maxsize: int = 32
    # Async-RL correctness: "strict" rejects any sample whose policy_version
    # differs from the current one; "bounded" allows lag <= max_policy_lag.
    # During today's evolve phase weights are static (lag 0 by construction);
    # the gate is the invariant check that makes overlap modes safe later.
    staleness_mode: str = "bounded"
    max_policy_lag: int = 1
    # Per-sample JSONL logging (accepted AND rejected) to rq_archive/.
    log_samples: bool = True
    # --- filtering semantics -------------------------------------------------
    # Rejected samples leave the p_hat denominator (p_hat = correct/accepted),
    # so each filter that can bias the curriculum estimate is a knob:
    #   reject_overlong: a truncated response is ambiguous (can't tell if the
    #     model would have solved it) -> rejected by default.
    #   reject_duplicates: identical rollouts are legitimate samples of the
    #     policy; dropping them biases p_hat on low-entropy problems -> default
    #     False (duplicates are DETECTED and counted in metrics/JSONL either way).
    #   reject_invalid_answer: a response with no \boxed{} DID fail the problem;
    #     removing it from the denominator would overestimate p_hat -> default
    #     False (counted as correct=false, flagged in metrics/JSONL either way).
    reject_overlong: bool = True
    reject_duplicates: bool = False
    reject_invalid_answer: bool = False
    # Where the uncertainty (actor-forward entropy) pass runs. Only "deferred"
    # is implemented: one batched FSDP forward after the last chunk drains,
    # identical memory profile to the legacy path (no contention with vLLM
    # generation on the colocated GPUs).
    entropy_mode: str = "deferred"

    def __post_init__(self) -> None:
        if self.staleness_mode not in ("strict", "bounded"):
            raise ValueError(
                f"async_rollout.staleness_mode must be 'strict' or 'bounded', "
                f"got {self.staleness_mode!r}"
            )
        if self.entropy_mode != "deferred":
            raise ValueError(
                f"async_rollout.entropy_mode: only 'deferred' is implemented, "
                f"got {self.entropy_mode!r}"
            )
        if self.chunk_size < 1:
            raise ValueError("async_rollout.chunk_size must be >= 1")
        if self.max_in_flight_chunks < 1:
            raise ValueError("async_rollout.max_in_flight_chunks must be >= 1")
        if self.max_policy_lag < 0:
            raise ValueError("async_rollout.max_policy_lag must be >= 0")
        # NOTE: unlike queue.Queue, 0 does NOT mean unbounded here -- it would
        # gate every submission off and hang the scheduler, so reject it.
        if self.queue_maxsize < 1:
            raise ValueError(
                "async_rollout.queue_maxsize must be >= 1 (it bounds the "
                "completed-chunk backlog; 0 is not 'unbounded')"
            )
        if self.request_timeout_s <= 0:
            raise ValueError("async_rollout.request_timeout_s must be > 0")
        if self.max_retries < 0:
            raise ValueError("async_rollout.max_retries must be >= 0")
        if self.verify_workers < 1:
            raise ValueError("async_rollout.verify_workers must be >= 1")


@dataclass(slots=True)
class LoraConfig:
    """LoRA settings plumbed into verl (actor_rollout_ref.model.lora_*).

    Disabled in the base configs (existing full-finetune runs unchanged);
    enabled in the smoke/DeepSeek configs. NOTE: the installed verl 0.7.1
    legacy FSDP worker does not plumb lora_dropout into peft -- effective
    dropout is 0.0 and a warning is printed when dropout > 0 is configured.
    """

    enabled: bool = False
    rank: int = 32
    alpha: int = 64
    dropout: float = 0.05
    # Standard attention/MLP projections (Qwen/Llama naming). Models with other
    # module names (e.g. DeepSeek MLA: q_a_proj/q_b_proj/kv_a_proj_with_mqa/
    # kv_b_proj) must override this; scripts/preflight_check.py prints matched
    # modules per pattern and fails early if any pattern matches nothing.
    target_modules: tuple[str, ...] = (
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    )
    # How trainer LoRA weights reach the vLLM rollout engine:
    #   auto           -> native_adapter if vLLM supports LoRA for the model
    #                     class, else fail with guidance (merge_push is a
    #                     documented future path, see docs/deepseek_support_plan.md)
    #   native_adapter -> verl's TensorLoRARequest/add_lora push (Qwen3 etc.)
    #   merge_push     -> NOT IMPLEMENTED (fails early); merged full-weight push
    #                     for models without vLLM LoRA support (DeepSeek MoE)
    sync_mode: str = "auto"

    def __post_init__(self) -> None:
        if self.sync_mode not in ("auto", "native_adapter", "merge_push"):
            raise ValueError(
                f"lora.sync_mode must be auto|native_adapter|merge_push, "
                f"got {self.sync_mode!r}"
            )
        if self.enabled and self.rank <= 0:
            raise ValueError("lora.enabled requires lora.rank > 0")


@dataclass(slots=True)
class MathEvalConfig:
    """Benchmark validation, ported from evo-sample's math_eval section.

    When enabled, the listed benchmarks are tokenized into a verl validation
    dataset (one ``data_source`` per benchmark). ``RQValidatingTrainer._validate``
    (eval_trainer.py) reports per-benchmark accuracy; grading reuses the training
    ``reward_function`` (sympy ``answers_match``) but runs on the trainer's MAIN
    thread (the agent-loop reward worker skips eval rows) so math_verify's SIGALRM
    timeout works and a pathological boxed answer can't stall the GPU mid-eval.
    GPT-judge is intentionally dropped. Evaluation cadence (before-train / every N
    steps) is controlled by ``trainer.val_before_train`` and ``trainer.test_freq``.
    """

    enabled: bool = False
    benchmarks: tuple[str, ...] = (
        "math500",
        "amc23",
        "aime24",
        "aime25",
        "minerva_math",
        "olympiadbench",
    )
    # Sub-sample per benchmark for quick debugging; -1 = full set (R-Zero parity).
    max_samples_per_benchmark: int = -1
    sample_seed: int = 42
    inflate_x32: bool = False
    grader: str = "sympy"


@dataclass(slots=True)
class RQEvolveConfig:
    archive: ArchiveConfig = field(default_factory=ArchiveConfig)
    evolution: EvolutionConfig = field(default_factory=EvolutionConfig)
    training_data: TrainingDataConfig = field(default_factory=TrainingDataConfig)
    verl: VerlConfig = field(default_factory=VerlConfig)
    math_eval: MathEvalConfig = field(default_factory=MathEvalConfig)
    async_rollout: AsyncRolloutConfig = field(default_factory=AsyncRolloutConfig)
    lora: LoraConfig = field(default_factory=LoraConfig)

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "RQEvolveConfig":
        return _dataclass_from_dict(cls, payload)


def load_config(path: str | Path) -> RQEvolveConfig:
    """Load YAML via OmegaConf, with a tiny fallback for this simple config."""
    path = Path(path)
    raw = OmegaConf.to_container(OmegaConf.load(path), resolve=True)
    if not isinstance(raw, dict):
        raise ValueError(f"config root must be a mapping: {path}")
    return RQEvolveConfig.from_dict(raw)


def _load_minimal_yaml(path: Path) -> dict[str, Any]:
    """Parse the small YAML subset used by ``configs/rq_evolve.yaml``.

    This is not a general YAML parser. It supports nested mappings through
    indentation plus inline scalars/lists, which keeps the starter project
    runnable before optional dependencies are installed.
    """
    root: dict[str, Any] = {}
    stack: list[tuple[int, dict[str, Any]]] = [(0, root)]
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        key, sep, value = line.strip().partition(":")
        if not sep:
            raise ValueError(f"unsupported config line: {raw_line!r}")
        while stack and indent < stack[-1][0]:
            stack.pop()
        current = stack[-1][1]
        if not value.strip():
            child: dict[str, Any] = {}
            current[key] = child
            stack.append((indent + 2, child))
            continue
        current[key] = _parse_scalar(value.strip())
    return root


def _parse_scalar(value: str) -> Any:
    lowered = value.lower()
    if lowered == "null":
        return None
    if lowered == "true":
        return True
    if lowered == "false":
        return False
    if value.startswith("[") or value.startswith(("'", '"')):
        return ast.literal_eval(value)
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        return value


def _dataclass_from_dict(cls, payload: dict[str, Any]):
    kwargs = {}
    for item in fields(cls):
        if item.name in payload:
            value = payload[item.name]
        elif item.default is not MISSING:
            value = item.default
        else:
            value = item.default_factory()

        if isinstance(value, dict) and item.default_factory is not MISSING:
            default_obj = item.default_factory()
            if is_dataclass(default_obj):
                kwargs[item.name] = _dataclass_from_dict(type(default_obj), value)
                continue
            kwargs[item.name] = value
        elif item.name == "h_range" and isinstance(value, list):
            kwargs[item.name] = tuple(float(x) for x in value)
        elif item.name == "frontier_p_hat_range" and isinstance(value, list):
            kwargs[item.name] = tuple(float(x) for x in value)
        elif item.name == "target_modules" and isinstance(value, list):
            kwargs[item.name] = tuple(str(x) for x in value)
        else:
            kwargs[item.name] = value
    return cls(**kwargs)
