import random


def generate(seed):
    rng = random.Random(seed)

    # A two-sided band. The one-sided ballot problem closes with a single
    # reflection; bounding the walk on both sides does not, so the count comes
    # from an alternating sum over repeated reflections (or a transfer matrix).
    steps = rng.randint(18, 30)
    width = rng.randint(3, 6)
    # Both endpoints inside the band, so the count is neither 0 nor trivial.
    end = rng.choice([h for h in range(-width + 1, width) if (h - steps) % 2 == 0])

    # Transfer-matrix route: how many walks of each height after each step.
    counts = {0: 1}
    for _ in range(steps):
        nxt = {}
        for height, ways in counts.items():
            for move in (1, -1):
                new = height + move
                if -width < new < width:
                    nxt[new] = nxt.get(new, 0) + ways
        counts = nxt
    answer = counts.get(end, 0)

    # Independent route: the reflection series. Unconstrained walks minus the
    # images of the two absorbing walls, alternating over reflections in the
    # group generated by them.
    def unconstrained(displacement):
        if (steps + displacement) % 2 or abs(displacement) > steps:
            return 0
        ups = (steps + displacement) // 2
        result = 1
        for i in range(ups):
            result = result * (steps - i) // (i + 1)
        return result

    period = 2 * width
    check = 0
    for k in range(-steps // period - 2, steps // period + 3):
        check += unconstrained(end + 2 * period * k)
        check -= unconstrained(2 * width - end + 2 * period * k)
    assert answer == check, f"answer={answer} check={check}"

    problem = (
        f"A walk starts at 0 and takes {steps} steps, each +1 or -1. It must "
        f"stay strictly between -{width} and {width} at every point, and it "
        f"ends at {end}. How many such walks are there? State only the integer."
    )
    return problem, str(answer)


GROUP = "combinatorics"
SKILL = "counting"
